
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ygmg-running.cmwsnflsb4fy.ap-northeast-2.rds.amazonaws.com:3306/running
    username: ygmg
    password: ssafyssafy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: k8c107.p.ssafy.io
    port: 5672
    username: guest
    password: guest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
